#!/bin/bash
if [[ $# -eq 1 ]];then
	project=$1
	if [[ ! -z $project ]];then
		/system/makedir /user/arduino/$project
		cd /user/arduino/$project;platformio init --board=nanoatmega328
	fi
else
	echo "Specify dirname for /user/arduino/dirname"
fi
