#!/bin/bash
# TODO add possibilities to select platform
# TODO quiet mode (with log ?)

#1/2/3 ARGUMENTS
if [ $# -eq 0 ] || [ $# -gt 3 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [platformio] [arduino]"
	/show/usageDescription "Compile and upload a sketch on an arduino"
	/show/usage "$0 folder or $0 folder (from /user/arduino) or $0 folder port or $0 folder port platform or $0 folder platform"
	/show/example "$0 radio2serial or $0 /home/pi/blink or $0 radio2serial /dev/ttyUSB1 nano or $0 radio2serial nano"
else
	dir=$1
	platform=""
	port=""

	#Check if port/platform has been specified
	if [ $# -ge 2 ];then	
		#If port exists
		checkdev=$(dirname $2)
		if [[ "$checkdev" == "/dev" ]];then
				port="--upload-port $2"
		else
			#TODO: Check if platform exists
			platform="--environment $2"
		fi
	fi

	#Check if platform/port has been specified (even in the wrong order)
	if [ $# -eq 3 ];then
		checkdev=$(dirname $3)
		echo $checkdev
		if [[ "$checkdev" == "/dev" ]];then
			port="--upload-port $3"
		else
			#TODO: Check if platform exists
			platform="--environment $3"
		fi
	fi

	#Check if we have a relative or absolute dir
	if [ -d "/user/arduino/$dir" ];then
           dir="/user/arduino/$dir"
    fi

	if [ -z "$platform" ]; then
    	platform_name="ANY ARDUINO"
	else
		platform_name=$platform
	fi

	if [ -z "$port" ]; then
		port_name="ANY PORT"
	else
		port_name=$port
	fi

	/show/description "[UPLOAD] $dir"
	/show/listecho "$port_name" $OK
	/show/listecho "$platform_name" $OK
	#Check if the directory exists
	if [ -d "$dir" ];then
		platformio -f run -d $dir $port $platform
	else
		/show/listecho "Folder doesn't exists" $ERR
	fi
fi

