#!/bin/bash

#No argument
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [platformio] [update]"
	/show/usageDescription "Update platformio"
	/show/usage "$0"
else
	/show/description "[PLATFORMIO] Update"
	platformio update
	/pi/updateGitRepo /user/arduino
fi
